# Generated by Django 5.2.17 on 2026-08-11 16:13

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('media_library', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order_number', models.CharField(max_length=64, unique=True)),
                ('order_type', models.CharField(max_length=80)),
                ('confirmation_status', models.CharField(choices=[('inquiry', '询价中'), ('proposed', '已报价'), ('confirmed', '已确认'), ('cancelled', '已取消')], default='inquiry', max_length=16)),
                ('agreed_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('deposit_status', models.CharField(choices=[('not_recorded', '未记录'), ('pending', '待线下确认'), ('recorded', '已人工记录'), ('waived', '无需收取')], default='not_recorded', max_length=16)),
                ('final_payment_status', models.CharField(choices=[('not_recorded', '未记录'), ('pending', '待线下确认'), ('recorded', '已人工记录'), ('waived', '无需收取')], default='not_recorded', max_length=16)),
                ('delivery_status', models.CharField(choices=[('not_ready', '未交付'), ('ready', '待交付'), ('delivered', '已交付')], default='not_ready', max_length=16)),
                ('notes', models.TextField(blank=True, max_length=5000)),
                ('is_dev_data', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='accounts.customerprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClientProject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=180)),
                ('description', models.TextField(blank=True, max_length=10000)),
                ('status', models.CharField(choices=[('planning', '筹备中'), ('active', '制作中'), ('paused', '已暂停'), ('review', '待验收'), ('completed', '已完成'), ('cancelled', '已取消')], default='planning', max_length=16)),
                ('completion_percent', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('next_plan', models.CharField(blank=True, max_length=500)),
                ('expected_next_update_at', models.DateTimeField(blank=True, null=True)),
                ('is_dev_data', models.BooleanField(default=False)),
                ('manager', models.ForeignKey(blank=True, limit_choices_to={'role': 'staff'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_projects', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='projects.order')),
            ],
            options={
                'ordering': ['-updated_at', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ProductionStage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', '待开始'), ('active', '进行中'), ('completed', '已完成'), ('skipped', '已跳过')], default='pending', max_length=16)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='projects.clientproject')),
            ],
            options={
                'ordering': ['sort_order', 'created_at'],
            },
        ),
        migrations.AddField(
            model_name='clientproject',
            name='current_stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_for_projects', to='projects.productionstage'),
        ),
        migrations.CreateModel(
            name='ProgressUpdate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=180)),
                ('body', models.TextField(max_length=12000)),
                ('next_plan', models.CharField(blank=True, max_length=500)),
                ('expected_next_update_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', '草稿'), ('published', '已发布')], default='draft', max_length=16)),
                ('requires_acknowledgement', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('is_dev_data', models.BooleanField(default=False)),
                ('author', models.ForeignKey(limit_choices_to={'role': 'staff'}, on_delete=django.db.models.deletion.PROTECT, related_name='authored_progress_updates', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_updates', to='projects.clientproject')),
                ('stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updates', to='projects.productionstage')),
            ],
            options={
                'ordering': ['-published_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProgressReceipt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('viewed_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_receipts', to=settings.AUTH_USER_MODEL)),
                ('update', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='projects.progressupdate')),
            ],
        ),
        migrations.CreateModel(
            name='ProgressImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('caption', models.CharField(blank=True, max_length=500)),
                ('alt_text', models.CharField(max_length=240)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='progress_images', to='media_library.mediaasset')),
                ('update', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='projects.progressupdate')),
            ],
            options={
                'ordering': ['sort_order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectMembership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('owner', '主要客户'), ('viewer', '查看成员')], default='viewer', max_length=16)),
                ('is_active', models.BooleanField(default=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='projects.clientproject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('body', models.TextField(max_length=3000)),
                ('is_dev_data', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='project_messages', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='projects.projectmessage')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='projects.clientproject')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectMessageReceipt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='projects.projectmessage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_receipts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('agreed_amount__isnull', True), ('agreed_amount__gte', 0), _connector='OR'), name='projects_order_amount_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='productionstage',
            constraint=models.UniqueConstraint(fields=('project', 'sort_order'), name='projects_unique_stage_order'),
        ),
        migrations.AddConstraint(
            model_name='clientproject',
            constraint=models.CheckConstraint(condition=models.Q(('completion_percent__gte', 0), ('completion_percent__lte', 100)), name='projects_client_completion_0_100'),
        ),
        migrations.AddConstraint(
            model_name='progressupdate',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'published'), _negated=True), ('published_at__isnull', False), _connector='OR'), name='projects_published_update_has_timestamp'),
        ),
        migrations.AddConstraint(
            model_name='progressreceipt',
            constraint=models.UniqueConstraint(fields=('update', 'user'), name='projects_unique_progress_receipt'),
        ),
        migrations.AddConstraint(
            model_name='progressimage',
            constraint=models.UniqueConstraint(fields=('update', 'sort_order'), name='projects_unique_progress_image_order'),
        ),
        migrations.AddConstraint(
            model_name='projectmembership',
            constraint=models.UniqueConstraint(fields=('project', 'user'), name='projects_unique_project_member'),
        ),
        migrations.AddConstraint(
            model_name='projectmessagereceipt',
            constraint=models.UniqueConstraint(fields=('message', 'user'), name='projects_unique_message_receipt'),
        ),
    ]
