# Generated by Django 5.2.17 on 2026-08-16 14:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


def initialize_transaction_fields(apps, schema_editor):
    Order = apps.get_model("projects", "Order")
    for order in Order.objects.all().iterator():
        order.final_amount = order.agreed_amount or 0
        if order.confirmation_status == "cancelled":
            order.payment_status = "cancelled"
        elif order.confirmation_status == "confirmed":
            if order.deposit_status == "pending":
                order.payment_status = "deposit_pending"
            elif order.final_payment_status in {"recorded", "waived"}:
                order.payment_status = "paid"
            else:
                order.payment_status = "final_pending"
        order.save(update_fields=["final_amount", "payment_status"])


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_username_length_and_chinese_names'),
        ('projects', '0004_require_message_dedupe'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment_type', models.CharField(choices=[('deposit', '定金'), ('final', '尾款'), ('refund', '退款')], max_length=16, verbose_name='付款类型')),
                ('channel', models.CharField(choices=[('mock', '本地模拟')], default='mock', max_length=16, verbose_name='支付渠道')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='金额')),
                ('status', models.CharField(choices=[('pending', '待支付'), ('succeeded', '成功'), ('failed', '失败'), ('refunded', '已退款')], default='pending', max_length=16, verbose_name='状态')),
                ('mock_transaction_id', models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='模拟交易号')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='支付时间')),
                ('notes', models.CharField(blank=True, max_length=1000, verbose_name='备注')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='元数据')),
            ],
            options={
                'verbose_name': '付款记录',
                'verbose_name_plural': '付款记录',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='currency',
            field=models.CharField(choices=[('CNY', '人民币')], default='CNY', max_length=3, verbose_name='币种'),
        ),
        migrations.AddField(
            model_name='order',
            name='deposit_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='定金金额'),
        ),
        migrations.AddField(
            model_name='order',
            name='final_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='尾款金额'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('unpaid', '未付款'), ('deposit_pending', '定金待支付'), ('deposit_paid', '定金已支付'), ('final_pending', '尾款待支付'), ('paid', '已付清'), ('cancelled', '已取消'), ('refunded', '已退款')], default='unpaid', max_length=24, verbose_name='付款状态'),
        ),
        migrations.AddField(
            model_name='order',
            name='quote_valid_until',
            field=models.DateTimeField(blank=True, null=True, verbose_name='报价有效期'),
        ),
        migrations.AlterField(
            model_name='order',
            name='agreed_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='订单金额（报价）'),
        ),
        migrations.RunPython(initialize_transaction_fields, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('deposit_amount__gte', 0)), name='projects_order_deposit_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('final_amount__gte', 0)), name='projects_order_final_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(
                condition=(
                    models.Q(agreed_amount__isnull=True, deposit_amount=0, final_amount=0)
                    | models.Q(agreed_amount=models.F('deposit_amount') + models.F('final_amount'))
                ),
                name='projects_order_amounts_match_total',
            ),
        ),
        migrations.AddField(
            model_name='paymentrecord',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_records', to='projects.order', verbose_name='订单'),
        ),
        migrations.AddConstraint(
            model_name='paymentrecord',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='projects_payment_amount_positive'),
        ),
    ]
