# Generated by Django 5.2.17 on 2026-08-16 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_username_length_and_chinese_names'),
        ('projects', '0005_paymentrecord_order_currency_order_deposit_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentrecord',
            name='currency',
            field=models.CharField(choices=[('CNY', '人民币')], default='CNY', max_length=3, verbose_name='币种'),
        ),
        migrations.AddField(
            model_name='paymentrecord',
            name='idempotency_key',
            field=models.CharField(blank=True, editable=False, max_length=160, null=True, unique=True, verbose_name='幂等标识'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('currency', 'CNY')), name='projects_order_currency_supported'),
        ),
        migrations.AddConstraint(
            model_name='paymentrecord',
            constraint=models.CheckConstraint(condition=models.Q(('currency', 'CNY')), name='projects_payment_currency_supported'),
        ),
    ]
