# Generated by Django 5.2.17 on 2026-08-16 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_paymentrecord_currency_paymentrecord_idempotency_key_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='order',
            name='projects_order_currency_supported',
        ),
        migrations.RemoveConstraint(
            model_name='paymentrecord',
            name='projects_payment_currency_supported',
        ),
        migrations.AlterField(
            model_name='order',
            name='currency',
            field=models.CharField(choices=[('CNY', '人民币'), ('USD', '美元')], default='CNY', max_length=3, verbose_name='币种'),
        ),
        migrations.AlterField(
            model_name='paymentrecord',
            name='currency',
            field=models.CharField(choices=[('CNY', '人民币'), ('USD', '美元')], default='CNY', max_length=3, verbose_name='币种'),
        ),
    ]
