# Generated by Django 5.2.17 on 2026-08-16 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_username_length_and_chinese_names'),
        ('projects', '0007_remove_order_projects_order_currency_supported_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('currency__in', ('CNY', 'USD'))), name='projects_order_currency_iso_supported'),
        ),
        migrations.AddConstraint(
            model_name='paymentrecord',
            constraint=models.CheckConstraint(condition=models.Q(('currency__in', ('CNY', 'USD'))), name='projects_payment_currency_iso_supported'),
        ),
    ]
