# Generated by Django 5.2.17 on 2026-08-17 04:40

import django.db.models.deletion
import django.db.models.expressions
import uuid
from django.db import migrations, models


def backfill_checkout_fields(apps, schema_editor):
    Order = apps.get_model('projects', 'Order')
    Order.objects.filter(agreed_amount__isnull=False).update(service_subtotal=models.F('agreed_amount'))
    Order.objects.filter(quote_decision='accepted').update(
        checkout_status='confirmed',
        checkout_confirmed_at=models.F('quote_decision_at'),
    )


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_username_length_and_chinese_names'),
        ('projects', '0008_order_projects_order_currency_iso_supported_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderContactAddress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recipient_name', models.CharField(max_length=120, verbose_name='收件人姓名')),
                ('email', models.EmailField(max_length=254, verbose_name='邮箱')),
                ('phone', models.CharField(max_length=40, verbose_name='联系电话')),
                ('country_code', models.CharField(max_length=2, verbose_name='国家或地区代码')),
                ('region', models.CharField(blank=True, max_length=120, verbose_name='州/省')),
                ('city', models.CharField(max_length=120, verbose_name='城市')),
                ('address_line', models.CharField(max_length=500, verbose_name='详细地址')),
                ('postal_code', models.CharField(max_length=32, verbose_name='邮编')),
            ],
            options={
                'verbose_name': '订单联系与收货信息',
                'verbose_name_plural': '订单联系与收货信息',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='checkout_confirmed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='结账确认时间'),
        ),
        migrations.AddField(
            model_name='order',
            name='checkout_status',
            field=models.CharField(choices=[('not_started', '未开始结账'), ('pending', '待客户确认'), ('confirmed', '客户已确认')], default='not_started', max_length=16, verbose_name='结账状态'),
        ),
        migrations.AddField(
            model_name='order',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='折扣'),
        ),
        migrations.AddField(
            model_name='order',
            name='service_subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='商品或服务小计'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='运费'),
        ),
        migrations.AddField(
            model_name='order',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='税费'),
        ),
        migrations.RunPython(backfill_checkout_fields, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('service_subtotal__gte', 0)), name='projects_order_subtotal_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('shipping_amount__gte', 0)), name='projects_order_shipping_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('tax_amount__gte', 0)), name='projects_order_tax_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('discount_amount__gte', 0)), name='projects_order_discount_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('discount_amount__lte', django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(models.F('service_subtotal'), '+', models.F('shipping_amount')), '+', models.F('tax_amount')))), name='projects_order_discount_within_charges'),
        ),
        migrations.AddField(
            model_name='ordercontactaddress',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='contact_address', to='projects.order', verbose_name='订单'),
        ),
    ]
