# Generated by Django 5.2.17 on 2026-08-11 16:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('media_library', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=80, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_visible', models.BooleanField(default=False)),
                ('is_dev_data', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='StudioSetting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.SlugField(default='default', max_length=32, unique=True)),
                ('studio_name', models.CharField(default='知行造境', max_length=120)),
                ('studio_name_en', models.CharField(default='Zhixing Studio', max_length=120)),
                ('tagline', models.CharField(blank=True, max_length=240)),
                ('description', models.TextField(blank=True, max_length=3000)),
                ('contact_name', models.CharField(blank=True, max_length=80)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('wechat', models.CharField(blank=True, max_length=64)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('privacy_notice', models.TextField(blank=True, max_length=5000)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=160)),
                ('slug', models.SlugField(blank=True, max_length=180, unique=True)),
                ('summary', models.CharField(blank=True, max_length=300)),
                ('description', models.TextField(blank=True, max_length=10000)),
                ('status', models.CharField(choices=[('draft', '草稿'), ('published', '公开'), ('hidden', '隐藏'), ('archived', '归档')], default='draft', max_length=16)),
                ('is_featured', models.BooleanField(default=False)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('scale', models.CharField(blank=True, max_length=40)),
                ('dimensions', models.CharField(blank=True, max_length=120)),
                ('materials', models.CharField(blank=True, max_length=500)),
                ('period', models.CharField(blank=True, max_length=120)),
                ('authors', models.CharField(blank=True, max_length=500)),
                ('completion_percent', models.PositiveSmallIntegerField(default=100)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('is_dev_data', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='works', to='portfolio.category')),
            ],
            options={
                'ordering': ['sort_order', '-published_at', 'title'],
            },
        ),
        migrations.CreateModel(
            name='PublicProcessPost',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=180)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('summary', models.CharField(blank=True, max_length=300)),
                ('body', models.TextField(max_length=12000)),
                ('status', models.CharField(choices=[('draft', '草稿'), ('published', '公开'), ('hidden', '隐藏')], default='draft', max_length=16)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('is_dev_data', models.BooleanField(default=False)),
                ('work', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='public_process_posts', to='portfolio.work')),
            ],
            options={
                'ordering': ['-published_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('cover', '封面'), ('gallery', '作品图'), ('room', '空间细节')], default='gallery', max_length=16)),
                ('alt_text', models.CharField(max_length=240)),
                ('caption', models.CharField(blank=True, max_length=500)),
                ('room_name', models.CharField(blank=True, max_length=120)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('focal_x', models.DecimalField(decimal_places=2, default=50, max_digits=5)),
                ('focal_y', models.DecimalField(decimal_places=2, default=50, max_digits=5)),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_images', to='media_library.mediaasset')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='portfolio.work')),
            ],
            options={
                'ordering': ['sort_order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='PublicProcessImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('alt_text', models.CharField(max_length=240)),
                ('caption', models.CharField(blank=True, max_length=500)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='public_process_images', to='media_library.mediaasset')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='portfolio.publicprocesspost')),
            ],
            options={
                'ordering': ['sort_order', 'created_at'],
                'constraints': [models.UniqueConstraint(fields=('post', 'sort_order'), name='portfolio_unique_process_image_order')],
            },
        ),
        migrations.AddConstraint(
            model_name='work',
            constraint=models.CheckConstraint(condition=models.Q(('completion_percent__gte', 0), ('completion_percent__lte', 100)), name='portfolio_work_completion_0_100'),
        ),
        migrations.AddConstraint(
            model_name='work',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'published'), _negated=True), ('published_at__isnull', False), _connector='OR'), name='portfolio_published_work_has_timestamp'),
        ),
        migrations.AddConstraint(
            model_name='publicprocesspost',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'published'), _negated=True), ('published_at__isnull', False), _connector='OR'), name='portfolio_published_process_has_timestamp'),
        ),
        migrations.AddConstraint(
            model_name='workimage',
            constraint=models.UniqueConstraint(fields=('work', 'sort_order'), name='portfolio_unique_work_image_order'),
        ),
        migrations.AddConstraint(
            model_name='workimage',
            constraint=models.CheckConstraint(condition=models.Q(('focal_x__gte', 0), ('focal_x__lte', 100)), name='portfolio_work_image_focal_x'),
        ),
        migrations.AddConstraint(
            model_name='workimage',
            constraint=models.CheckConstraint(condition=models.Q(('focal_y__gte', 0), ('focal_y__lte', 100)), name='portfolio_work_image_focal_y'),
        ),
    ]
