# Generated by Django 5.2.17 on 2026-08-11 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studiosetting',
            name='is_dev_data',
            field=models.BooleanField(default=False),
        ),
    ]
