import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("portfolio", "0002_studiosetting_is_dev_data")]

    operations = [
        migrations.AlterModelOptions(name="category", options={"ordering": ["sort_order", "name"], "verbose_name": "作品分类", "verbose_name_plural": "作品分类"}),
        migrations.AlterModelOptions(name="work", options={"ordering": ["sort_order", "-published_at", "title"], "verbose_name": "作品", "verbose_name_plural": "作品"}),
        migrations.AlterModelOptions(name="workimage", options={"ordering": ["sort_order", "created_at"], "verbose_name": "作品图片", "verbose_name_plural": "作品图片"}),
        migrations.AlterModelOptions(name="publicprocesspost", options={"ordering": ["-published_at", "-created_at"], "verbose_name": "公开制作日志", "verbose_name_plural": "公开制作日志"}),
        migrations.AlterModelOptions(name="publicprocessimage", options={"ordering": ["sort_order", "created_at"], "verbose_name": "公开制作日志图片", "verbose_name_plural": "公开制作日志图片"}),
        migrations.AlterModelOptions(name="studiosetting", options={"verbose_name": "工作室设置", "verbose_name_plural": "工作室设置"}),
        migrations.AlterField(model_name="category", name="name", field=models.CharField(max_length=80, unique=True, verbose_name="分类名称")),
        migrations.AlterField(model_name="category", name="slug", field=models.SlugField(blank=True, max_length=100, unique=True, verbose_name="网址标识")),
        migrations.AlterField(model_name="category", name="description", field=models.CharField(blank=True, max_length=300, verbose_name="分类说明")),
        migrations.AlterField(model_name="category", name="sort_order", field=models.PositiveIntegerField(default=0, verbose_name="排序")),
        migrations.AlterField(model_name="category", name="is_visible", field=models.BooleanField(default=False, verbose_name="公开显示")),
        migrations.AlterField(model_name="category", name="is_dev_data", field=models.BooleanField(default=False, verbose_name="开发测试数据")),
        migrations.AlterField(model_name="work", name="category", field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="works", to="portfolio.category", verbose_name="作品分类")),
        migrations.AlterField(model_name="work", name="title", field=models.CharField(max_length=160, verbose_name="作品标题")),
        migrations.AlterField(model_name="work", name="slug", field=models.SlugField(blank=True, max_length=180, unique=True, verbose_name="网址标识")),
        migrations.AlterField(model_name="work", name="summary", field=models.CharField(blank=True, max_length=300, verbose_name="作品摘要")),
        migrations.AlterField(model_name="work", name="description", field=models.TextField(blank=True, max_length=10000, verbose_name="作品说明")),
        migrations.AlterField(model_name="work", name="status", field=models.CharField(choices=[("draft", "草稿"), ("published", "公开"), ("hidden", "隐藏"), ("archived", "归档")], default="draft", max_length=16, verbose_name="发布状态")),
        migrations.AlterField(model_name="work", name="is_featured", field=models.BooleanField(default=False, verbose_name="代表作品")),
        migrations.AlterField(model_name="work", name="sort_order", field=models.PositiveIntegerField(default=0, verbose_name="排序")),
        migrations.AlterField(model_name="work", name="scale", field=models.CharField(blank=True, max_length=40, verbose_name="模型比例")),
        migrations.AlterField(model_name="work", name="dimensions", field=models.CharField(blank=True, max_length=120, verbose_name="尺寸")),
        migrations.AlterField(model_name="work", name="materials", field=models.CharField(blank=True, max_length=500, verbose_name="材料")),
        migrations.AlterField(model_name="work", name="period", field=models.CharField(blank=True, max_length=120, verbose_name="制作时期")),
        migrations.AlterField(model_name="work", name="authors", field=models.CharField(blank=True, max_length=500, verbose_name="制作者")),
        migrations.AlterField(model_name="work", name="completion_percent", field=models.PositiveSmallIntegerField(default=100, verbose_name="完成百分比")),
        migrations.AlterField(model_name="work", name="published_at", field=models.DateTimeField(blank=True, null=True, verbose_name="发布时间")),
        migrations.AlterField(model_name="work", name="is_dev_data", field=models.BooleanField(default=False, verbose_name="开发测试数据")),
        migrations.AlterField(model_name="workimage", name="work", field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="images", to="portfolio.work", verbose_name="作品")),
        migrations.AlterField(model_name="workimage", name="media", field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="work_images", to="media_library.mediaasset", verbose_name="媒体文件")),
        migrations.AlterField(model_name="workimage", name="kind", field=models.CharField(choices=[("cover", "封面"), ("gallery", "作品图"), ("room", "空间细节")], default="gallery", max_length=16, verbose_name="图片用途")),
        migrations.AlterField(model_name="workimage", name="alt_text", field=models.CharField(max_length=240, verbose_name="替代文字")),
        migrations.AlterField(model_name="workimage", name="caption", field=models.CharField(blank=True, max_length=500, verbose_name="图片说明")),
        migrations.AlterField(model_name="workimage", name="room_name", field=models.CharField(blank=True, max_length=120, verbose_name="空间名称")),
        migrations.AlterField(model_name="workimage", name="sort_order", field=models.PositiveIntegerField(default=0, verbose_name="排序")),
        migrations.AlterField(model_name="workimage", name="focal_x", field=models.DecimalField(decimal_places=2, default=50, max_digits=5, verbose_name="水平焦点（%）")),
        migrations.AlterField(model_name="workimage", name="focal_y", field=models.DecimalField(decimal_places=2, default=50, max_digits=5, verbose_name="垂直焦点（%）")),
        migrations.AlterField(model_name="publicprocesspost", name="work", field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="public_process_posts", to="portfolio.work", verbose_name="关联作品")),
        migrations.AlterField(model_name="publicprocesspost", name="title", field=models.CharField(max_length=180, verbose_name="日志标题")),
        migrations.AlterField(model_name="publicprocesspost", name="slug", field=models.SlugField(blank=True, max_length=200, unique=True, verbose_name="网址标识")),
        migrations.AlterField(model_name="publicprocesspost", name="summary", field=models.CharField(blank=True, max_length=300, verbose_name="日志摘要")),
        migrations.AlterField(model_name="publicprocesspost", name="body", field=models.TextField(max_length=12000, verbose_name="日志正文")),
        migrations.AlterField(model_name="publicprocesspost", name="status", field=models.CharField(choices=[("draft", "草稿"), ("published", "公开"), ("hidden", "隐藏")], default="draft", max_length=16, verbose_name="发布状态")),
        migrations.AlterField(model_name="publicprocesspost", name="published_at", field=models.DateTimeField(blank=True, null=True, verbose_name="发布时间")),
        migrations.AlterField(model_name="publicprocesspost", name="is_dev_data", field=models.BooleanField(default=False, verbose_name="开发测试数据")),
        migrations.AlterField(model_name="publicprocessimage", name="post", field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="images", to="portfolio.publicprocesspost", verbose_name="公开制作日志")),
        migrations.AlterField(model_name="publicprocessimage", name="media", field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="public_process_images", to="media_library.mediaasset", verbose_name="媒体文件")),
        migrations.AlterField(model_name="publicprocessimage", name="alt_text", field=models.CharField(max_length=240, verbose_name="替代文字")),
        migrations.AlterField(model_name="publicprocessimage", name="caption", field=models.CharField(blank=True, max_length=500, verbose_name="图片说明")),
        migrations.AlterField(model_name="publicprocessimage", name="sort_order", field=models.PositiveIntegerField(default=0, verbose_name="排序")),
        migrations.AlterField(model_name="studiosetting", name="key", field=models.SlugField(default="default", max_length=32, unique=True, verbose_name="设置标识")),
        migrations.AlterField(model_name="studiosetting", name="studio_name", field=models.CharField(default="知行造境", max_length=120, verbose_name="工作室名称")),
        migrations.AlterField(model_name="studiosetting", name="studio_name_en", field=models.CharField(default="Zhixing Studio", max_length=120, verbose_name="英文名称")),
        migrations.AlterField(model_name="studiosetting", name="tagline", field=models.CharField(blank=True, max_length=240, verbose_name="简介标题")),
        migrations.AlterField(model_name="studiosetting", name="description", field=models.TextField(blank=True, max_length=3000, verbose_name="工作室说明")),
        migrations.AlterField(model_name="studiosetting", name="contact_name", field=models.CharField(blank=True, max_length=80, verbose_name="联系人")),
        migrations.AlterField(model_name="studiosetting", name="phone", field=models.CharField(blank=True, max_length=32, verbose_name="电话")),
        migrations.AlterField(model_name="studiosetting", name="wechat", field=models.CharField(blank=True, max_length=64, verbose_name="微信")),
        migrations.AlterField(model_name="studiosetting", name="email", field=models.EmailField(blank=True, max_length=254, verbose_name="邮箱")),
        migrations.AlterField(model_name="studiosetting", name="privacy_notice", field=models.TextField(blank=True, max_length=5000, verbose_name="隐私说明")),
        migrations.AlterField(model_name="studiosetting", name="is_dev_data", field=models.BooleanField(default=False, verbose_name="开发测试数据")),
    ]
