# Generated by Django 5.2.17 on 2026-08-16 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_chinese_model_names'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description_en',
            field=models.CharField(blank=True, max_length=300, verbose_name='英文分类说明'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_en',
            field=models.CharField(blank=True, max_length=80, verbose_name='英文分类名称'),
        ),
        migrations.AddField(
            model_name='publicprocessimage',
            name='alt_text_en',
            field=models.CharField(blank=True, max_length=240, verbose_name='英文替代文字'),
        ),
        migrations.AddField(
            model_name='publicprocessimage',
            name='caption_en',
            field=models.CharField(blank=True, max_length=500, verbose_name='英文图片说明'),
        ),
        migrations.AddField(
            model_name='publicprocesspost',
            name='body_en',
            field=models.TextField(blank=True, max_length=12000, verbose_name='英文日志正文'),
        ),
        migrations.AddField(
            model_name='publicprocesspost',
            name='summary_en',
            field=models.CharField(blank=True, max_length=300, verbose_name='英文日志摘要'),
        ),
        migrations.AddField(
            model_name='publicprocesspost',
            name='title_en',
            field=models.CharField(blank=True, max_length=180, verbose_name='英文日志标题'),
        ),
        migrations.AddField(
            model_name='studiosetting',
            name='description_en',
            field=models.TextField(blank=True, max_length=3000, verbose_name='英文工作室说明'),
        ),
        migrations.AddField(
            model_name='studiosetting',
            name='privacy_notice_en',
            field=models.TextField(blank=True, max_length=5000, verbose_name='英文隐私说明'),
        ),
        migrations.AddField(
            model_name='studiosetting',
            name='tagline_en',
            field=models.CharField(blank=True, max_length=240, verbose_name='英文简介标题'),
        ),
        migrations.AddField(
            model_name='work',
            name='authors_en',
            field=models.CharField(blank=True, max_length=500, verbose_name='英文制作者'),
        ),
        migrations.AddField(
            model_name='work',
            name='description_en',
            field=models.TextField(blank=True, max_length=10000, verbose_name='英文作品说明'),
        ),
        migrations.AddField(
            model_name='work',
            name='dimensions_en',
            field=models.CharField(blank=True, max_length=120, verbose_name='英文尺寸'),
        ),
        migrations.AddField(
            model_name='work',
            name='materials_en',
            field=models.CharField(blank=True, max_length=500, verbose_name='英文材料'),
        ),
        migrations.AddField(
            model_name='work',
            name='period_en',
            field=models.CharField(blank=True, max_length=120, verbose_name='英文制作时期'),
        ),
        migrations.AddField(
            model_name='work',
            name='scale_en',
            field=models.CharField(blank=True, max_length=40, verbose_name='英文模型比例'),
        ),
        migrations.AddField(
            model_name='work',
            name='summary_en',
            field=models.CharField(blank=True, max_length=300, verbose_name='英文作品摘要'),
        ),
        migrations.AddField(
            model_name='work',
            name='title_en',
            field=models.CharField(blank=True, max_length=160, verbose_name='英文作品标题'),
        ),
        migrations.AddField(
            model_name='workimage',
            name='alt_text_en',
            field=models.CharField(blank=True, max_length=240, verbose_name='英文替代文字'),
        ),
        migrations.AddField(
            model_name='workimage',
            name='caption_en',
            field=models.CharField(blank=True, max_length=500, verbose_name='英文图片说明'),
        ),
        migrations.AddField(
            model_name='workimage',
            name='room_name_en',
            field=models.CharField(blank=True, max_length=120, verbose_name='英文空间名称'),
        ),
    ]
