# Generated by Django 5.2.17 on 2026-08-11 16:13

import django.db.models.deletion
import media_library.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaAsset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('access', models.CharField(choices=[('public', '公开'), ('private', '私人')], max_length=16)),
                ('kind', models.CharField(choices=[('work', '作品'), ('public_process', '公开制作日志'), ('progress', '客户进度'), ('inquiry', '询价附件'), ('studio', '工作室资料')], max_length=32)),
                ('original', models.ImageField(max_length=500, upload_to=media_library.models.original_upload_path)),
                ('display', models.ImageField(blank=True, max_length=500, upload_to=media_library.models.display_upload_path)),
                ('thumbnail', models.ImageField(blank=True, max_length=500, upload_to=media_library.models.thumbnail_upload_path)),
                ('original_name', models.CharField(blank=True, editable=False, max_length=255)),
                ('declared_content_type', models.CharField(blank=True, editable=False, max_length=100)),
                ('detected_content_type', models.CharField(blank=True, editable=False, max_length=100)),
                ('size_bytes', models.PositiveBigIntegerField(default=0, editable=False)),
                ('width', models.PositiveIntegerField(default=0, editable=False)),
                ('height', models.PositiveIntegerField(default=0, editable=False)),
                ('sha256', models.CharField(blank=True, db_index=True, editable=False, max_length=64)),
                ('is_dev_data', models.BooleanField(default=False)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_media', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['access', 'kind', 'created_at'], name='media_libra_access_dcbf58_idx')],
            },
        ),
    ]
