# Generated by Django 5.2.17 on 2026-08-11 16:13

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('media_library', '0001_initial'),
        ('portfolio', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=80)),
                ('contact_type', models.CharField(choices=[('phone', '手机号'), ('wechat', '微信')], max_length=16)),
                ('contact_value', models.CharField(max_length=80)),
                ('project_type', models.CharField(max_length=100)),
                ('scale', models.CharField(blank=True, max_length=40)),
                ('budget_range', models.CharField(blank=True, max_length=80)),
                ('expected_delivery_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(max_length=5000)),
                ('privacy_consent', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('new', '新询价'), ('contacted', '已联系'), ('closed', '已关闭'), ('spam', '垃圾信息')], default='new', max_length=16)),
                ('is_dev_data', models.BooleanField(default=False)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_inquiries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InquiryAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('inquiry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='interactions.inquiry')),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inquiry_attachments', to='media_library.mediaasset')),
            ],
            options={
                'ordering': ['sort_order', 'created_at'],
                'constraints': [models.UniqueConstraint(fields=('inquiry', 'sort_order'), name='interactions_unique_inquiry_attachment_order')],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewer_name', models.CharField(max_length=80)),
                ('project_name', models.CharField(max_length=160)),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField(max_length=2000)),
                ('status', models.CharField(choices=[('pending', '待审核'), ('approved', '已批准'), ('rejected', '已拒绝')], default='pending', max_length=16)),
                ('moderated_at', models.DateTimeField(blank=True, null=True)),
                ('is_dev_data', models.BooleanField(default=False)),
                ('moderated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderated_reviews', to=settings.AUTH_USER_MODEL)),
                ('work', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='portfolio.work')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(('rating__gte', 1), ('rating__lte', 5)), name='interactions_review_rating_1_5')],
            },
        ),
    ]
